<?php declare(strict_types=1);

namespace Amp\Http\Internal;

/** @internal */
const HEADER_LOWERCASE_MAP = [
    'Accept' => 'accept',
    'accept' => 'accept',
    'Accept-Encoding' => 'accept-encoding',
    'accept-encoding' => 'accept-encoding',
    'Accept-Language' => 'accept-language',
    'accept-language' => 'accept-language',
    'Authorization' => 'authorization',
    'authorization' => 'authorization',
    'Cache-Control' => 'cache-control',
    'cache-control' => 'cache-control',
    'Connection' => 'connection',
    'connection' => 'connection',
    'Content-Encoding' => 'content-encoding',
    'content-encoding' => 'content-encoding',
    'Cookie' => 'cookie',
    'cookie' => 'cookie',
    'Date' => 'date',
    'date' => 'date',
    'Host' => 'host',
    'host' => 'host',
    'Sec-Fetch-Dest' => 'sec-fetch-dest',
    'sec-fetch-dest' => 'sec-fetch-dest',
    'Sec-Fetch-Mode' => 'sec-fetch-mode',
    'sec-fetch-mode' => 'sec-fetch-mode',
    'Sec-Fetch-Site' => 'sec-fetch-site',
    'sec-fetch-site' => 'sec-fetch-site',
    'Sec-Fetch-User' => 'sec-fetch-user',
    'sec-fetch-user' => 'sec-fetch-user',
    'Set-Cookie' => 'set-cookie',
    'set-cookie' => 'set-cookie',
    'Strict-Transport-Security' => 'strict-transport-security',
    'strict-transport-security' => 'strict-transport-security',
    'Upgrade-Insecure-Requests' => 'upgrade-insecure-requests',
    'upgrade-insecure-requests' => 'upgrade-insecure-requests',
    'User-Agent' => 'user-agent',
    'user-agent' => 'user-agent',
    'Vary' => 'vary',
    'vary' => 'vary',
];
